"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input } from "@/components/ui/field";
import { useUpdateSeatCount } from "@/hooks/use-libraries";
import { ApiError, messageFor } from "@/lib/api-error";
import { MAX_SEAT_COUNT } from "@/schemas/admin";
import { seatCountSchema, type SeatCountValues } from "@/schemas/seat";
import type { LibraryResponse } from "@/types/api";

/**
 * Library configuration: how many seats the library has.
 *
 * Rendered only for a caller holding LIBRARY_UPDATE, which V1 grants to
 * SUPER_ADMIN and ORGANIZATION_OWNER alone - receptionists, accountants, library
 * managers and staff never see it. That is presentation, not protection: the
 * backend refuses the call for anyone else and for any library the caller is not
 * a member of, so hiding the panel only keeps the screen honest.
 *
 * Individual seat numbers are absent by design. They are generated by the
 * backend from this figure and are not editable anywhere in the product.
 */
export function SeatCountPanel({ library }: { library: LibraryResponse }) {
  const update = useUpdateSeatCount(library.libraryId);

  const {
    register,
    handleSubmit,
    reset,
    setError,
    formState: { errors },
  } = useForm<SeatCountValues>({
    resolver: zodResolver(seatCountSchema),
    defaultValues: { seatCount: String(library.seatCount ?? 0) },
  });

  // Switching library, or a successful change, re-seeds the input from what the
  // backend now reports rather than leaving the previously typed number behind.
  useEffect(() => {
    reset({ seatCount: String(library.seatCount ?? 0) });
  }, [library.libraryId, library.seatCount, reset]);

  // Both failures are about the number that was typed, so they belong on the
  // field: a count outside the allowed range, and a reduction the backend
  // refused because a surplus seat is allocated or carries attendance history.
  useEffect(() => {
    if (!(update.error instanceof ApiError)) return;

    const code = update.error.errorCode;
    if (code === "INVALID_SEAT_COUNT" || code === "SEAT_COUNT_REDUCTION_BLOCKED") {
      setError("seatCount", { type: "server", message: messageFor(update.error) });
    }
  }, [update.error, setError]);

  const formLevelError =
    update.error instanceof ApiError
    && !["INVALID_SEAT_COUNT", "SEAT_COUNT_REDUCTION_BLOCKED"].includes(
      update.error.errorCode ?? "",
    )
      ? messageFor(update.error)
      : null;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Library configuration</CardTitle>
      </CardHeader>

      <form
        className="p-5"
        onSubmit={handleSubmit((values) =>
          update.mutate({ seatCount: Number(values.seatCount) }),
        )}
        noValidate
      >
        {formLevelError ? (
          <div
            role="alert"
            className="mb-4 rounded-lg border border-danger-100 bg-danger-50 px-3 py-2.5 text-sm text-danger-700"
          >
            {formLevelError}
          </div>
        ) : null}

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <p className="text-[13px] text-ink3">Current number of seats</p>
            <p className="text-2xl font-semibold text-ink">{library.seatCount ?? 0}</p>
            <p className="text-[12px] text-ink3">{library.name}</p>
          </div>

          <Field
            label="Number of seats"
            htmlFor="seatCount"
            required
            hint={`The system creates the seats and numbers them. Up to ${MAX_SEAT_COUNT}.`}
            error={errors.seatCount?.message}
          >
            <Input
              id="seatCount"
              type="number"
              inputMode="numeric"
              min={1}
              max={MAX_SEAT_COUNT}
              step={1}
              invalid={Boolean(errors.seatCount)}
              {...register("seatCount")}
            />
          </Field>
        </div>

        <p className="mt-3 text-[13px] text-ink3">
          Seats are numbered by the system and cannot be renumbered. Raising this adds only the
          missing seats, and existing seats keep their number and status. Lowering it removes the
          surplus seats, except any that carry allocation or attendance history - those are kept
          out of service so nothing is lost - and is refused outright while one is in use.
        </p>

        <div className="mt-5 flex justify-end border-t border-linesoft pt-4">
          <Button type="submit" loading={update.isPending}>
            Save
          </Button>
        </div>
      </form>
    </Card>
  );
}
